
import { blog1, blog2, blog3, user } from "./images"


export const servicesData = [
    {
      id: "blog-1",
      image: blog1,
      title: "Dolor clita vero elitr sea stet dolor justo diam",
      content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
      profile: user,
      name: "John Doe",
      views: "12345",
      comments: "123",
    },
    {
        id: "blog-2",
        image: blog2,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-3",
        image: blog3,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-4",
        image: blog2,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-4",
        image: blog3,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-5",
        image: blog1,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-6",
        image: blog1,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-7",
        image: blog2,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-8",
        image: blog3,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },
      {
        id: "blog-9",
        image: blog1,
        title: "Dolor clita vero elitr sea stet dolor justo diam",
        content: "Dolor lorem eos dolor duo et eirmod sea. Dolor sit magna rebum clita rebum dolor stet amet justo",
        profile: user,
        name: "John Doe",
        views: "12345",
        comments: "123",
      },

]

